### ISSUE TITLE
I cannot get the module to work, I followed the instructions, but i get an error of needing to do a "/log config". So I uninstalled the mod and I still get your Adventure Log in the right click menu even AFTER uninstalling your mod. [BUG]

### ISSUE THREAD

**Issue by ghost** [Grygon/adventure-log#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Foundry version [e.g. 0.6.6]
 - System in use [e.g. Lancer]
 - Other modules in use [Please remove as many as possible]

**Additional context**

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
e.g. Grygon#1234
![Screenshot 2021-03-10 183216](https://user-images.githubusercontent.com/79125274/110722089-f9418980-81ce-11eb-82ef-15bf165a0b98.png)

**Comment by Grygon** [comment]
Ah, I think you're thinking of [df-chat-enhancement's Adventure Log feature](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance#Adventure-Log)
